#!/bin/bash
# Shared setup for all demo run.sh scripts.
# Sources .workshop_env (generated by verify.sh) to detect auth mode.
# Sets CLAUDE_FLAGS that each run.sh appends to its claude command.

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
Q="$(cat "$REPO/demo/QUESTION.txt")"

# Load .env if present (for ANTHROPIC_API_KEY)
if [ -f "$REPO/.env" ]; then
    set -a
    source "$REPO/.env"
    set +a
fi

# Model: override with DEMO_MODEL env var (e.g., DEMO_MODEL=haiku for speed)
MODEL="${DEMO_MODEL:-sonnet}"

# --bare is critical: skips CLAUDE.md auto-discovery, hooks, plugins.
# Without it, Claude crawls the entire repo and takes 2-3 minutes.
# --bare requires ANTHROPIC_API_KEY (loaded from .env above).
CLAUDE_FLAGS="-p --bare --model $MODEL --dangerously-skip-permissions"

# Scorer helper — silently skips if evaluate.py is absent (students)
score_output() {
    local output_file="$1"
    local question="$2"
    echo ""
    echo "━━━ SCORE ━━━"
    local scorer=""
    for candidate in "$REPO/presenter/evaluate.py" "$REPO/benchmark/evaluate.py"; do
        [ -f "$candidate" ] && scorer="$candidate" && break
    done
    if [ -n "$scorer" ]; then
        python3 "$scorer" --input "$output_file" --quick --question "$question"
    else
        echo "(scorer not available — presenters run scoring separately)"
    fi
}
