#!/bin/bash
# Shared setup for all demo run.sh scripts.
# Sources .workshop_env (generated by verify.sh) to detect auth mode.
# Sets CLAUDE_FLAGS that each run.sh appends to its claude command.

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
Q="$(cat "$REPO/demo/QUESTION.txt")"

# Load auth mode from verify.sh
ENV_FILE="$REPO/.workshop_env"
if [ -f "$ENV_FILE" ]; then
    source "$ENV_FILE"
else
    # Fallback detection if verify.sh wasn't run
    if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
        CLAUDE_AUTH_MODE=apikey
    else
        CLAUDE_AUTH_MODE=oauth
    fi
fi

# Build flags based on auth mode
# --bare is faster but requires ANTHROPIC_API_KEY (no OAuth).
# Plain -p works with both OAuth and API key.
if [ "$CLAUDE_AUTH_MODE" = "apikey" ]; then
    CLAUDE_FLAGS="-p --bare --model sonnet --dangerously-skip-permissions"
else
    CLAUDE_FLAGS="-p --model sonnet --dangerously-skip-permissions"
fi

# Scorer helper — silently skips if evaluate.py is absent (students)
score_output() {
    local output_file="$1"
    local question="$2"
    echo ""
    echo "━━━ SCORE ━━━"
    local scorer=""
    for candidate in "$REPO/presenter/evaluate.py" "$REPO/benchmark/evaluate.py"; do
        [ -f "$candidate" ] && scorer="$candidate" && break
    done
    if [ -n "$scorer" ]; then
        python3 "$scorer" --input "$output_file" --quick --question "$question"
    else
        echo "(scorer not available — presenters run scoring separately)"
    fi
}
